# Generated by Django 4.2.9 on 2025-11-10 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bombonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateTimeField(verbose_name='Data da Coleta')),
                ('peso_coletado', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso Coletado (kg)')),
                ('destino', models.CharField(help_text='Local para onde os resíduos foram enviados', max_length=300, verbose_name='Destino')),
                ('empresa_destino', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa de Destino')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('numero_manifesto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Manifesto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('bombona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas', to='bombonas.bombona', verbose_name='Bombona')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coletas', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Coleta',
                'verbose_name_plural': 'Coletas',
                'ordering': ['-data_coleta'],
                'indexes': [models.Index(fields=['-data_coleta'], name='coletas_col_data_co_e2bc0f_idx'), models.Index(fields=['bombona'], name='coletas_col_bombona_0a77a9_idx'), models.Index(fields=['operador'], name='coletas_col_operado_39ef69_idx'), models.Index(fields=['status'], name='coletas_col_status_131a52_idx')],
            },
        ),
    ]
