# Generated by Django 4.2.9 on 2025-11-10 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bombona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=100, unique=True, verbose_name='Identificação')),
                ('codigo_qr', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Código QR')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('endereco_instalacao', models.CharField(max_length=300, verbose_name='Endereço de Instalação')),
                ('capacidade', models.DecimalField(decimal_places=2, help_text='Capacidade máxima em quilogramas', max_digits=8, verbose_name='Capacidade (kg)')),
                ('tipo_residuo', models.CharField(choices=[('organico', 'Orgânico'), ('reciclavel', 'Reciclável'), ('eletronico', 'Eletrônico'), ('quimico', 'Químico'), ('hospitalar', 'Hospitalar'), ('perigoso', 'Perigoso'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Resíduo')),
                ('descricao_residuo', models.TextField(blank=True, null=True, verbose_name='Descrição do Resíduo')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('quase_cheia', 'Quase Cheia'), ('cheia', 'Cheia'), ('manutencao', 'Manutenção'), ('inativa', 'Inativa')], default='normal', max_length=20, verbose_name='Status')),
                ('peso_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Peso Atual (kg)')),
                ('temperatura', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Temperatura (°C)')),
                ('ultima_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Última Leitura')),
                ('data_instalacao', models.DateField(verbose_name='Data de Instalação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bombonas', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Bombona',
                'verbose_name_plural': 'Bombonas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso (kg)')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura (°C)')),
                ('data_leitura', models.DateTimeField(auto_now_add=True, verbose_name='Data da Leitura')),
                ('simulado', models.BooleanField(default=True, verbose_name='Leitura Simulada')),
                ('bombona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='bombonas.bombona', verbose_name='Bombona')),
            ],
            options={
                'verbose_name': 'Leitura de Sensor',
                'verbose_name_plural': 'Leituras de Sensores',
                'ordering': ['-data_leitura'],
                'indexes': [models.Index(fields=['bombona', '-data_leitura'], name='bombonas_le_bombona_c1d290_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bombona',
            index=models.Index(fields=['identificacao'], name='bombonas_bo_identif_5e246b_idx'),
        ),
        migrations.AddIndex(
            model_name='bombona',
            index=models.Index(fields=['empresa'], name='bombonas_bo_empresa_52bcda_idx'),
        ),
        migrations.AddIndex(
            model_name='bombona',
            index=models.Index(fields=['status'], name='bombonas_bo_status_d9dd19_idx'),
        ),
        migrations.AddIndex(
            model_name='bombona',
            index=models.Index(fields=['tipo_residuo'], name='bombonas_bo_tipo_re_d288f7_idx'),
        ),
    ]
