# Generated by Django 4.2.9 on 2025-11-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bombonas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombona',
            name='tipo_residuo',
            field=models.CharField(choices=[('hospitalar_infectante', 'Hospitalar Infectante (Classe A)'), ('hospitalar_quimico', 'Hospitalar Químico (Classe B)'), ('hospitalar_radioativo', 'Hospitalar Radioativo (Classe C)'), ('hospitalar_perfurocortante', 'Hospitalar Perfurocortante (Classe E)'), ('industrial_toxico', 'Industrial Tóxico'), ('solventes_organicos', 'Solventes Orgânicos'), ('metais_pesados', 'Metais Pesados'), ('acidos_bases', 'Ácidos e Bases'), ('laboratorio_quimico', 'Laboratório Químico'), ('farmaceutico', 'Farmacêutico'), ('outros_perigosos', 'Outros Perigosos')], max_length=30, verbose_name='Tipo de Resíduo'),
        ),
    ]
