# Generated by Django 4.2.9 on 2025-11-10 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bombonas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nivel_alto', 'Nível Alto'), ('nivel_critico', 'Nível Crítico'), ('temperatura_alta', 'Temperatura Alta'), ('manutencao', 'Manutenção Necessária'), ('sensor_falha', 'Falha no Sensor'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('nivel', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=20, verbose_name='Nível')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('observacoes_resolucao', models.TextField(blank=True, null=True, verbose_name='Observações da Resolução')),
                ('data_alerta', models.DateTimeField(auto_now_add=True, verbose_name='Data do Alerta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('bombona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='bombonas.bombona', verbose_name='Bombona')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-data_alerta'],
                'indexes': [models.Index(fields=['-data_alerta'], name='alertas_ale_data_al_de5d38_idx'), models.Index(fields=['bombona'], name='alertas_ale_bombona_beb550_idx'), models.Index(fields=['resolvido'], name='alertas_ale_resolvi_6bc679_idx'), models.Index(fields=['nivel'], name='alertas_ale_nivel_9f1d56_idx')],
            },
        ),
    ]
